import { TechniqueModel } from '../common/models/technique';

export function techniqueTestData(): TechniqueModel[] {
    return [
        {
            id: 0,
            description: '',
            grade: 1,
            title: 'Makko Chigi 1',
            techniqueSet: {
                id: 1,
                name: 'Makko Chigi',
            },
            tags: [],
            questions: [],
            media: [
                {
                    id: 186,
                    file_name: '37_329ce6a5',
                    file_type: 'mp4',
                    folder: '8/37/videos',
                    original_file_name: '1_06797abe.mp4',
                    publishedStatus: 'Draft',
                    uploadStatus: 'Uploaded',
                    size: '9919421',
                    views: 3,
                    url:
                        'https://hapkido-convert-videos.s3-ap-southeast-2.amazonaws.com/8/37/videos/37_329ce6a5/Default/',
                    updatedAt: new Date('2020-12-07T01:02:18.000Z'),
                    tags: [],
                },
            ],
            isUnwatched: false,
            isAvailable: true,
            isFavourite: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 1,
            description: '',
            grade: 3,
            title: 'Makko Chigi 2',
            techniqueSet: {
                id: 1,
                name: 'Makko Chigi',
            },
            tags: [],
            questions: [],
            media: [
                {
                    id: 186,
                    file_name: '37_329ce6a5',
                    file_type: 'mp4',
                    folder: '8/37/videos',
                    original_file_name: '1_06797abe.mp4',
                    publishedStatus: 'Draft',
                    uploadStatus: 'Uploaded',
                    size: '9919421',
                    views: 3,
                    url:
                        'https://hapkido-convert-videos.s3-ap-southeast-2.amazonaws.com/8/37/videos/37_329ce6a5/Default/',
                    updatedAt: new Date('2020-12-07T01:02:18.000Z'),
                    tags: [],
                },
            ],
            isUnwatched: true,
            isAvailable: true,
            isFavourite: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 2,
            description: '',
            grade: 5,
            title: 'Son Mok Su 1',
            techniqueSet: {
                id: 2,
                name: 'Son Mok Su',
            },
            tags: [],
            questions: [],
            media: [],
            isUnwatched: true,
            isAvailable: true,
            isFavourite: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 3,
            description: '',
            grade: 7,
            title: 'Son Mok Su 2',
            techniqueSet: {
                id: 2,
                name: 'Son Mok Su',
            },
            tags: [],
            questions: [],
            media: [],
            isUnwatched: true,
            isAvailable: true,
            isFavourite: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 4,
            description: '',
            grade: 9,
            title: 'Ee Bok Su 8',
            techniqueSet: {
                id: 3,
                name: 'Ee Bok Su',
            },
            tags: [],
            questions: [],
            media: [],
            isUnwatched: false,
            isAvailable: false,
            isFavourite: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            id: 5,
            description: '',
            grade: 11,
            title: 'Ee Bok Su 9',
            techniqueSet: {
                id: 3,
                name: 'Ee Bok Su',
            },
            tags: [],
            questions: [],
            media: [],
            isUnwatched: false,
            isAvailable: false,
            isFavourite: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];
}
